using System.Collections.Generic;

namespace ClrDebug.Native
{
    internal class CorError
    {
        public const int E_NOINTERFACE = unchecked((int)0x80004002);

        public const int E_POINTER = unchecked((int)0x80004003);

        public const string NoResourceStringMessage = "An error has occurred.";

        public const string NoResourceIdMessage = "UnknownCorError";

        public static readonly Dictionary<int, (string Id, string Message)> s_errorMap;

        static CorError()
        {
            unchecked
            {
                s_errorMap = new Dictionary<int, (string Id, string Message)>()
                {
                    { HResult.CLDB_S_TRUNCATION, (nameof(HResult.CLDB_S_TRUNCATION), "STATUS: Data value was truncated.") },
                    { HResult.META_S_DUPLICATE, (nameof(HResult.META_S_DUPLICATE), "Attempt to define an object that already exists in valid scenerios.") },
                    { HResult.CORDBG_S_BAD_START_SEQUENCE_POINT, (nameof(HResult.CORDBG_S_BAD_START_SEQUENCE_POINT), "Attempt to SetIP not at a sequence point sequence point.") },
                    { HResult.CORDBG_S_BAD_END_SEQUENCE_POINT, (nameof(HResult.CORDBG_S_BAD_END_SEQUENCE_POINT), "Attempt to SetIP when not going to a sequence point. If both this and CORDBG_E_BAD_START_SEQUENCE_POINT are true, only CORDBG_E_BAD_START_SEQUENCE_POINT will be reported.") },
                    { HResult.CORDBG_S_FUNC_EVAL_HAS_NO_RESULT, (nameof(HResult.CORDBG_S_FUNC_EVAL_HAS_NO_RESULT), "Some Func evals will lack a return value,") },
                    { HResult.CORDBG_S_VALUE_POINTS_TO_VOID, (nameof(HResult.CORDBG_S_VALUE_POINTS_TO_VOID), "The Debugging API doesn't support dereferencing void pointers.") },
                    { HResult.CORDBG_S_FUNC_EVAL_ABORTED, (nameof(HResult.CORDBG_S_FUNC_EVAL_ABORTED), "The func eval completed, but was aborted.") },
                    { HResult.CORDBG_S_AT_END_OF_STACK, (nameof(HResult.CORDBG_S_AT_END_OF_STACK), "The stack walk has reached the end of the stack.  There are no more frames to walk.") },
                    { HResult.CORDBG_S_NOT_ALL_BITS_SET, (nameof(HResult.CORDBG_S_NOT_ALL_BITS_SET), "Not all bits specified were successfully applied") },
                    { HResult.CEE_E_CVTRES_NOT_FOUND, (nameof(HResult.CEE_E_CVTRES_NOT_FOUND), "cvtres.exe not found.") },
                    { HResult.COR_E_TYPEUNLOADED, (nameof(HResult.COR_E_TYPEUNLOADED), "Type has been unloaded.") },
                    { HResult.COR_E_APPDOMAINUNLOADED, (nameof(HResult.COR_E_APPDOMAINUNLOADED), "Attempted to access an unloaded appdomain.") },
                    { HResult.COR_E_CANNOTUNLOADAPPDOMAIN, (nameof(HResult.COR_E_CANNOTUNLOADAPPDOMAIN), "Error while unloading appdomain.") },
                    { HResult.MSEE_E_ASSEMBLYLOADINPROGRESS, (nameof(HResult.MSEE_E_ASSEMBLYLOADINPROGRESS), "Assembly is still being loaded.") },
                    { HResult.COR_E_ASSEMBLYEXPECTED, (nameof(HResult.COR_E_ASSEMBLYEXPECTED), "The module was expected to contain an assembly manifest.") },
                    { HResult.COR_E_FIXUPSINEXE, (nameof(HResult.COR_E_FIXUPSINEXE), "Attempt to load an unverifiable executable with fixups (IAT with more than 2 sections or a TLS section.)") },
                    { HResult.COR_E_NEWER_RUNTIME, (nameof(HResult.COR_E_NEWER_RUNTIME), "This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded.") },
                    { HResult.COR_E_MULTIMODULEASSEMBLIESDIALLOWED, (nameof(HResult.COR_E_MULTIMODULEASSEMBLIESDIALLOWED), "The module cannot be loaded because only single file assemblies are supported.") },
                    { HResult.HOST_E_DEADLOCK, (nameof(HResult.HOST_E_DEADLOCK), "Host detected a deadlock on a blocking operation.") },
                    { HResult.HOST_E_INVALIDOPERATION, (nameof(HResult.HOST_E_INVALIDOPERATION), "Invalid operation.") },
                    { HResult.HOST_E_CLRNOTAVAILABLE, (nameof(HResult.HOST_E_CLRNOTAVAILABLE), "CLR has been disabled due to unrecoverable error.") },
                    { HResult.HOST_E_EXITPROCESS_THREADABORT, (nameof(HResult.HOST_E_EXITPROCESS_THREADABORT), "Process exited due to ThreadAbort escalation.") },
                    { HResult.HOST_E_EXITPROCESS_ADUNLOAD, (nameof(HResult.HOST_E_EXITPROCESS_ADUNLOAD), "Process exited due to AD Unload escalation.") },
                    { HResult.HOST_E_EXITPROCESS_TIMEOUT, (nameof(HResult.HOST_E_EXITPROCESS_TIMEOUT), "Process exited due to Timeout escalation.") },
                    { HResult.HOST_E_EXITPROCESS_OUTOFMEMORY, (nameof(HResult.HOST_E_EXITPROCESS_OUTOFMEMORY), "Process exited due to OutOfMemory escalation.") },
                    { HResult.COR_E_MODULE_HASH_CHECK_FAILED, (nameof(HResult.COR_E_MODULE_HASH_CHECK_FAILED), "The check of the module's hash failed.") },
                    { HResult.FUSION_E_REF_DEF_MISMATCH, (nameof(HResult.FUSION_E_REF_DEF_MISMATCH), "The located assembly's manifest definition does not match the assembly reference.") },
                    { HResult.FUSION_E_INVALID_PRIVATE_ASM_LOCATION, (nameof(HResult.FUSION_E_INVALID_PRIVATE_ASM_LOCATION), "The private assembly was located outside the appbase directory.") },
                    { HResult.FUSION_E_ASM_MODULE_MISSING, (nameof(HResult.FUSION_E_ASM_MODULE_MISSING), "A module specified in the manifest was not found.") },
                    { HResult.FUSION_E_PRIVATE_ASM_DISALLOWED, (nameof(HResult.FUSION_E_PRIVATE_ASM_DISALLOWED), "A strongly-named assembly is required.") },
                    { HResult.FUSION_E_SIGNATURE_CHECK_FAILED, (nameof(HResult.FUSION_E_SIGNATURE_CHECK_FAILED), "Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key.") },
                    { HResult.FUSION_E_INVALID_NAME, (nameof(HResult.FUSION_E_INVALID_NAME), "The given assembly name or codebase was invalid.") },
                    { HResult.FUSION_E_CODE_DOWNLOAD_DISABLED, (nameof(HResult.FUSION_E_CODE_DOWNLOAD_DISABLED), "HTTP download of assemblies has been disabled for this appdomain.") },
                    { HResult.FUSION_E_HOST_GAC_ASM_MISMATCH, (nameof(HResult.FUSION_E_HOST_GAC_ASM_MISMATCH), "Assembly in host store has a different signature than assembly in GAC.") },
                    { HResult.FUSION_E_LOADFROM_BLOCKED, (nameof(HResult.FUSION_E_LOADFROM_BLOCKED), "LoadFrom(), LoadFile(), Load(byte[]) and LoadModule() have been disabled by the host.") },
                    { HResult.FUSION_E_CACHEFILE_FAILED, (nameof(HResult.FUSION_E_CACHEFILE_FAILED), "Failed to add file to AppDomain cache.") },
                    { HResult.FUSION_E_APP_DOMAIN_LOCKED, (nameof(HResult.FUSION_E_APP_DOMAIN_LOCKED), "The requested assembly version conflicts with what is already bound in the app domain or specified in the manifest.") },
                    { HResult.FUSION_E_CONFIGURATION_ERROR, (nameof(HResult.FUSION_E_CONFIGURATION_ERROR), "The requested assembly name was neither found in the GAC nor in the manifest or the manifest's specified location is wrong.") },
                    { HResult.FUSION_E_MANIFEST_PARSE_ERROR, (nameof(HResult.FUSION_E_MANIFEST_PARSE_ERROR), "Unexpected error while parsing the specified manifest.") },
                    { HResult.COR_E_LOADING_REFERENCE_ASSEMBLY, (nameof(HResult.COR_E_LOADING_REFERENCE_ASSEMBLY), "Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context.") },
                    { HResult.COR_E_NI_AND_RUNTIME_VERSION_MISMATCH, (nameof(HResult.COR_E_NI_AND_RUNTIME_VERSION_MISMATCH), "The native image could not be loaded, because it was generated for use by a different version of the runtime.") },
                    { HResult.COR_E_LOADING_WINMD_REFERENCE_ASSEMBLY, (nameof(HResult.COR_E_LOADING_WINMD_REFERENCE_ASSEMBLY), "Contract Windows Runtime assemblies cannot be loaded for execution.  Make sure your application only contains non-contract Windows Runtime assemblies.") },
                    { HResult.COR_E_AMBIGUOUSIMPLEMENTATION, (nameof(HResult.COR_E_AMBIGUOUSIMPLEMENTATION), "Ambiguous implementation found.") },
                    { HResult.CLDB_E_FILE_BADREAD, (nameof(HResult.CLDB_E_FILE_BADREAD), "Error occurred during a read.") },
                    { HResult.CLDB_E_FILE_BADWRITE, (nameof(HResult.CLDB_E_FILE_BADWRITE), "Error occurred during a write.") },
                    { HResult.CLDB_E_FILE_OLDVER, (nameof(HResult.CLDB_E_FILE_OLDVER), "Old version error.") },
                    { HResult.CLDB_E_SMDUPLICATE, (nameof(HResult.CLDB_E_SMDUPLICATE), "Create of shared memory failed.  A memory mapping of the same name already exists.") },
                    { HResult.CLDB_E_NO_DATA, (nameof(HResult.CLDB_E_NO_DATA), "No .CLB data in the memory or stream.") },
                    { HResult.CLDB_E_INCOMPATIBLE, (nameof(HResult.CLDB_E_INCOMPATIBLE), "Importing scope is not compatible with the emitting scope.") },
                    { HResult.CLDB_E_FILE_CORRUPT, (nameof(HResult.CLDB_E_FILE_CORRUPT), "File is corrupt.") },
                    { HResult.CLDB_E_BADUPDATEMODE, (nameof(HResult.CLDB_E_BADUPDATEMODE), "Cannot open a incrementally build scope for full update.") },
                    { HResult.CLDB_E_INDEX_NOTFOUND, (nameof(HResult.CLDB_E_INDEX_NOTFOUND), "Index not found.") },
                    { HResult.CLDB_E_RECORD_NOTFOUND, (nameof(HResult.CLDB_E_RECORD_NOTFOUND), "Record not found on lookup.") },
                    { HResult.CLDB_E_RECORD_OUTOFORDER, (nameof(HResult.CLDB_E_RECORD_OUTOFORDER), "Record is emitted out of order.") },
                    { HResult.CLDB_E_TOO_BIG, (nameof(HResult.CLDB_E_TOO_BIG), "A blob or string was too big.") },
                    { HResult.META_E_INVALID_TOKEN_TYPE, (nameof(HResult.META_E_INVALID_TOKEN_TYPE), "A token of the wrong type passed to a metadata function.") },
                    { HResult.TLBX_E_LIBNOTREGISTERED, (nameof(HResult.TLBX_E_LIBNOTREGISTERED), "Typelib export: Type library is not registered.") },
                    { HResult.META_E_BADMETADATA, (nameof(HResult.META_E_BADMETADATA), "Merge: Inconsistency in meta data import scope.") },
                    { HResult.META_E_BAD_SIGNATURE, (nameof(HResult.META_E_BAD_SIGNATURE), "Bad binary signature.") },
                    { HResult.META_E_BAD_INPUT_PARAMETER, (nameof(HResult.META_E_BAD_INPUT_PARAMETER), "Bad input parameters.") },
                    { HResult.META_E_CANNOTRESOLVETYPEREF, (nameof(HResult.META_E_CANNOTRESOLVETYPEREF), "Cannot resolve typeref.") },
                    { HResult.META_E_STRINGSPACE_FULL, (nameof(HResult.META_E_STRINGSPACE_FULL), "No logical space left to create more user strings.") },
                    { HResult.META_E_HAS_UNMARKALL, (nameof(HResult.META_E_HAS_UNMARKALL), "Unmark all has been called already.") },
                    { HResult.META_E_MUST_CALL_UNMARKALL, (nameof(HResult.META_E_MUST_CALL_UNMARKALL), "Must call UnmarkAll first before marking.") },
                    { HResult.META_E_CA_INVALID_TARGET, (nameof(HResult.META_E_CA_INVALID_TARGET), "Known custom attribute on invalid target.") },
                    { HResult.META_E_CA_INVALID_VALUE, (nameof(HResult.META_E_CA_INVALID_VALUE), "Known custom attribute had invalid value.") },
                    { HResult.META_E_CA_INVALID_BLOB, (nameof(HResult.META_E_CA_INVALID_BLOB), "Known custom attribute blob has bad format.") },
                    { HResult.META_E_CA_REPEATED_ARG, (nameof(HResult.META_E_CA_REPEATED_ARG), "Known custom attribute blob has repeated named argument.") },
                    { HResult.META_E_CA_UNKNOWN_ARGUMENT, (nameof(HResult.META_E_CA_UNKNOWN_ARGUMENT), "Known custom attribute named argument not recognized.") },
                    { HResult.META_E_CA_UNEXPECTED_TYPE, (nameof(HResult.META_E_CA_UNEXPECTED_TYPE), "Known attribute parser found unexpected type.") },
                    { HResult.META_E_CA_INVALID_ARGTYPE, (nameof(HResult.META_E_CA_INVALID_ARGTYPE), "Known attribute parser only handles fields, not properties.") },
                    { HResult.META_E_CA_INVALID_ARG_FOR_TYPE, (nameof(HResult.META_E_CA_INVALID_ARG_FOR_TYPE), "Known attribute parser found an argument that is invalid for the object it is applied to.") },
                    { HResult.META_E_CA_INVALID_UUID, (nameof(HResult.META_E_CA_INVALID_UUID), "The format of the UUID was invalid.") },
                    { HResult.META_E_CA_INVALID_MARSHALAS_FIELDS, (nameof(HResult.META_E_CA_INVALID_MARSHALAS_FIELDS), "The MarshalAs attribute has fields set that are not valid for the specified unmanaged type.") },
                    { HResult.META_E_CA_NT_FIELDONLY, (nameof(HResult.META_E_CA_NT_FIELDONLY), "The specified unmanaged type is only valid on fields.") },
                    { HResult.META_E_CA_NEGATIVE_PARAMINDEX, (nameof(HResult.META_E_CA_NEGATIVE_PARAMINDEX), "The parameter index cannot be negative.") },
                    { HResult.META_E_CA_NEGATIVE_CONSTSIZE, (nameof(HResult.META_E_CA_NEGATIVE_CONSTSIZE), "The constant size cannot be negative.") },
                    { HResult.META_E_CA_FIXEDSTR_SIZE_REQUIRED, (nameof(HResult.META_E_CA_FIXEDSTR_SIZE_REQUIRED), "A fixed string requires a size.") },
                    { HResult.META_E_CA_CUSTMARSH_TYPE_REQUIRED, (nameof(HResult.META_E_CA_CUSTMARSH_TYPE_REQUIRED), "A custom marshaler requires the custom marshaler type.") },
                    { HResult.META_E_NOT_IN_ENC_MODE, (nameof(HResult.META_E_NOT_IN_ENC_MODE), "SaveDelta was called without being in EnC mode.") },
                    { HResult.META_E_CA_BAD_FRIENDS_ARGS, (nameof(HResult.META_E_CA_BAD_FRIENDS_ARGS), "InternalsVisibleTo can't have a version, culture, or processor architecture.") },
                    { HResult.META_E_CA_FRIENDS_SN_REQUIRED, (nameof(HResult.META_E_CA_FRIENDS_SN_REQUIRED), "Strong-name signed assemblies can only grant friend access to strong name-signed assemblies") },
                    { HResult.VLDTR_E_RID_OUTOFRANGE, (nameof(HResult.VLDTR_E_RID_OUTOFRANGE), "Rid is out of range.") },
                    { HResult.VLDTR_E_STRING_INVALID, (nameof(HResult.VLDTR_E_STRING_INVALID), "String offset is invalid.") },
                    { HResult.VLDTR_E_GUID_INVALID, (nameof(HResult.VLDTR_E_GUID_INVALID), "GUID offset is invalid.") },
                    { HResult.VLDTR_E_BLOB_INVALID, (nameof(HResult.VLDTR_E_BLOB_INVALID), "Blob offset if invalid.") },
                    { HResult.VLDTR_E_MR_BADCALLINGCONV, (nameof(HResult.VLDTR_E_MR_BADCALLINGCONV), "MemberRef has invalid calling convention.") },
                    { HResult.VLDTR_E_SIGNULL, (nameof(HResult.VLDTR_E_SIGNULL), "Signature specified is zero-sized.") },
                    { HResult.VLDTR_E_MD_BADCALLINGCONV, (nameof(HResult.VLDTR_E_MD_BADCALLINGCONV), "Method signature has invalid calling convention.") },
                    { HResult.VLDTR_E_MD_THISSTATIC, (nameof(HResult.VLDTR_E_MD_THISSTATIC), "Method is marked static but has HASTHIS/EXPLICITTHIS set on the calling convention.") },
                    { HResult.VLDTR_E_MD_NOTTHISNOTSTATIC, (nameof(HResult.VLDTR_E_MD_NOTTHISNOTSTATIC), "Method is not marked static but is not HASTHIS or EXPLICITTHIS.") },
                    { HResult.VLDTR_E_MD_NOARGCNT, (nameof(HResult.VLDTR_E_MD_NOARGCNT), "Method signature is missing the argument count.") },
                    { HResult.VLDTR_E_SIG_MISSELTYPE, (nameof(HResult.VLDTR_E_SIG_MISSELTYPE), "Signature missing element type.") },
                    { HResult.VLDTR_E_SIG_MISSTKN, (nameof(HResult.VLDTR_E_SIG_MISSTKN), "Signature missing token.") },
                    { HResult.VLDTR_E_SIG_TKNBAD, (nameof(HResult.VLDTR_E_SIG_TKNBAD), "Signature has bad token.") },
                    { HResult.VLDTR_E_SIG_MISSFPTR, (nameof(HResult.VLDTR_E_SIG_MISSFPTR), "Signature is missing function pointer.") },
                    { HResult.VLDTR_E_SIG_MISSFPTRARGCNT, (nameof(HResult.VLDTR_E_SIG_MISSFPTRARGCNT), "Signature has function pointer missing argument count.") },
                    { HResult.VLDTR_E_SIG_MISSRANK, (nameof(HResult.VLDTR_E_SIG_MISSRANK), "Signature is missing rank specification.") },
                    { HResult.VLDTR_E_SIG_MISSNSIZE, (nameof(HResult.VLDTR_E_SIG_MISSNSIZE), "Signature is missing count of sized dimensions.") },
                    { HResult.VLDTR_E_SIG_MISSSIZE, (nameof(HResult.VLDTR_E_SIG_MISSSIZE), "Signature is missing size of dimension.") },
                    { HResult.VLDTR_E_SIG_MISSNLBND, (nameof(HResult.VLDTR_E_SIG_MISSNLBND), "Signature is missing count of lower bounds.") },
                    { HResult.VLDTR_E_SIG_MISSLBND, (nameof(HResult.VLDTR_E_SIG_MISSLBND), "Signature is missing a lower bound.") },
                    { HResult.VLDTR_E_SIG_BADELTYPE, (nameof(HResult.VLDTR_E_SIG_BADELTYPE), "Signature has bad element type.") },
                    { HResult.VLDTR_E_TD_ENCLNOTNESTED, (nameof(HResult.VLDTR_E_TD_ENCLNOTNESTED), "TypeDef not nested has encloser.") },
                    { HResult.VLDTR_E_FMD_PINVOKENOTSTATIC, (nameof(HResult.VLDTR_E_FMD_PINVOKENOTSTATIC), "Field or method is PInvoke but is not marked Static.") },
                    { HResult.VLDTR_E_SIG_SENTINMETHODDEF, (nameof(HResult.VLDTR_E_SIG_SENTINMETHODDEF), "E_T_SENTINEL in MethodDef signature.") },
                    { HResult.VLDTR_E_SIG_SENTMUSTVARARG, (nameof(HResult.VLDTR_E_SIG_SENTMUSTVARARG), "E_T_SENTINEL <=> VARARG.") },
                    { HResult.VLDTR_E_SIG_MULTSENTINELS, (nameof(HResult.VLDTR_E_SIG_MULTSENTINELS), "Multiple E_T_SENTINELs.") },
                    { HResult.VLDTR_E_SIG_MISSARG, (nameof(HResult.VLDTR_E_SIG_MISSARG), "Signature missing argument.") },
                    { HResult.VLDTR_E_SIG_BYREFINFIELD, (nameof(HResult.VLDTR_E_SIG_BYREFINFIELD), "Field of ByRef type.") },
                    { HResult.CORDBG_E_UNRECOVERABLE_ERROR, (nameof(HResult.CORDBG_E_UNRECOVERABLE_ERROR), "Unrecoverable API error.") },
                    { HResult.CORDBG_E_PROCESS_TERMINATED, (nameof(HResult.CORDBG_E_PROCESS_TERMINATED), "Process was terminated.") },
                    { HResult.CORDBG_E_PROCESS_NOT_SYNCHRONIZED, (nameof(HResult.CORDBG_E_PROCESS_NOT_SYNCHRONIZED), "Process not synchronized.") },
                    { HResult.CORDBG_E_CLASS_NOT_LOADED, (nameof(HResult.CORDBG_E_CLASS_NOT_LOADED), "A class is not loaded.") },
                    { HResult.CORDBG_E_IL_VAR_NOT_AVAILABLE, (nameof(HResult.CORDBG_E_IL_VAR_NOT_AVAILABLE), "An IL variable is not available at the current native IP.") },
                    { HResult.CORDBG_E_BAD_REFERENCE_VALUE, (nameof(HResult.CORDBG_E_BAD_REFERENCE_VALUE), "A reference value was found to be bad during dereferencing.") },
                    { HResult.CORDBG_E_FIELD_NOT_AVAILABLE, (nameof(HResult.CORDBG_E_FIELD_NOT_AVAILABLE), "A field in a class is not available, because the runtime optimized it away.") },
                    { HResult.CORDBG_E_NON_NATIVE_FRAME, (nameof(HResult.CORDBG_E_NON_NATIVE_FRAME), "'Native-frame-only' operation on non-native frame.") },
                    { HResult.CORDBG_E_CODE_NOT_AVAILABLE, (nameof(HResult.CORDBG_E_CODE_NOT_AVAILABLE), "The code is currently unavailable.") },
                    { HResult.CORDBG_E_FUNCTION_NOT_IL, (nameof(HResult.CORDBG_E_FUNCTION_NOT_IL), "Attempt to get a ICorDebugFunction for a function that is not IL.") },
                    { HResult.CORDBG_E_CANT_SET_IP_INTO_FINALLY, (nameof(HResult.CORDBG_E_CANT_SET_IP_INTO_FINALLY), "SetIP is not possible because SetIP would move EIP from outside of an exception handling finally clause to a point inside of one.") },
                    { HResult.CORDBG_E_CANT_SET_IP_OUT_OF_FINALLY, (nameof(HResult.CORDBG_E_CANT_SET_IP_OUT_OF_FINALLY), "SetIP is not possible because it would move EIP from within an exception handling finally clause to a point outside of one.") },
                    { HResult.CORDBG_E_CANT_SET_IP_INTO_CATCH, (nameof(HResult.CORDBG_E_CANT_SET_IP_INTO_CATCH), "SetIP is not possible, because SetIP would move EIP from outside of an exception handling catch clause to a point inside of one.") },
                    { HResult.CORDBG_E_SET_IP_NOT_ALLOWED_ON_NONLEAF_FRAME, (nameof(HResult.CORDBG_E_SET_IP_NOT_ALLOWED_ON_NONLEAF_FRAME), "SetIP cannot be done on any frame except the leaf frame.") },
                    { HResult.CORDBG_E_SET_IP_IMPOSSIBLE, (nameof(HResult.CORDBG_E_SET_IP_IMPOSSIBLE), "SetIP is not allowed.") },
                    { HResult.CORDBG_E_FUNC_EVAL_BAD_START_POINT, (nameof(HResult.CORDBG_E_FUNC_EVAL_BAD_START_POINT), "Func eval cannot work. Bad starting point.") },
                    { HResult.CORDBG_E_INVALID_OBJECT, (nameof(HResult.CORDBG_E_INVALID_OBJECT), "This object value is no longer valid.") },
                    { HResult.CORDBG_E_FUNC_EVAL_NOT_COMPLETE, (nameof(HResult.CORDBG_E_FUNC_EVAL_NOT_COMPLETE), "CordbEval::GetResult called before func eval has finished.") },
                    { HResult.CORDBG_E_STATIC_VAR_NOT_AVAILABLE, (nameof(HResult.CORDBG_E_STATIC_VAR_NOT_AVAILABLE), "A static variable is not available because it has not been initialized yet.") },
                    { HResult.CORDBG_E_CANT_SETIP_INTO_OR_OUT_OF_FILTER, (nameof(HResult.CORDBG_E_CANT_SETIP_INTO_OR_OUT_OF_FILTER), "SetIP cannot leave or enter a filter.") },
                    { HResult.CORDBG_E_CANT_CHANGE_JIT_SETTING_FOR_ZAP_MODULE, (nameof(HResult.CORDBG_E_CANT_CHANGE_JIT_SETTING_FOR_ZAP_MODULE), "JIT settings for ZAP modules cannot be changed.") },
                    { HResult.CORDBG_E_CANT_SET_IP_OUT_OF_FINALLY_ON_WIN64, (nameof(HResult.CORDBG_E_CANT_SET_IP_OUT_OF_FINALLY_ON_WIN64), "SetIP is not possible because it would move EIP from within a finally clause to a point outside of one on this platforms.") },
                    { HResult.CORDBG_E_CANT_SET_IP_OUT_OF_CATCH_ON_WIN64, (nameof(HResult.CORDBG_E_CANT_SET_IP_OUT_OF_CATCH_ON_WIN64), "SetIP is not possible because it would move EIP from within a catch clause to a point outside of one on this platforms.") },
                    { HResult.CORDBG_E_CANT_SET_TO_JMC, (nameof(HResult.CORDBG_E_CANT_SET_TO_JMC), "Cannot use JMC on this code (likely wrong JIT settings).") },
                    { HResult.CORDBG_E_NO_CONTEXT_FOR_INTERNAL_FRAME, (nameof(HResult.CORDBG_E_NO_CONTEXT_FOR_INTERNAL_FRAME), "Internal frame markers have no associated context.") },
                    { HResult.CORDBG_E_NOT_CHILD_FRAME, (nameof(HResult.CORDBG_E_NOT_CHILD_FRAME), "The current frame is not a child frame.") },
                    { HResult.CORDBG_E_NON_MATCHING_CONTEXT, (nameof(HResult.CORDBG_E_NON_MATCHING_CONTEXT), "The provided CONTEXT does not match the specified thread.") },
                    { HResult.CORDBG_E_PAST_END_OF_STACK, (nameof(HResult.CORDBG_E_PAST_END_OF_STACK), "The stackwalker is now past the end of stack.  No information is available.") },
                    { HResult.CORDBG_E_PAST_END_OF_STACK, (nameof(HResult.CORDBG_E_PAST_END_OF_STACK), "The stackwalker is now past the end of stack.  No information is available.") },
                    { HResult.CORDBG_E_BAD_THREAD_STATE, (nameof(HResult.CORDBG_E_BAD_THREAD_STATE), "The state of the thread is invalid.") },
                    { HResult.CORDBG_E_DEBUGGER_ALREADY_ATTACHED, (nameof(HResult.CORDBG_E_DEBUGGER_ALREADY_ATTACHED), "This process has already been attached.") },
                    { HResult.CORDBG_E_SUPERFLOUS_CONTINUE, (nameof(HResult.CORDBG_E_SUPERFLOUS_CONTINUE), "Returned from a call to Continue that was not matched with a stopping event.") },
                    { HResult.CORDBG_E_SET_VALUE_NOT_ALLOWED_ON_NONLEAF_FRAME, (nameof(HResult.CORDBG_E_SET_VALUE_NOT_ALLOWED_ON_NONLEAF_FRAME), "Cannot perfrom SetValue on non-leaf frames.") },
                    { HResult.CORDBG_E_ENC_MODULE_NOT_ENC_ENABLED, (nameof(HResult.CORDBG_E_ENC_MODULE_NOT_ENC_ENABLED), "Tried to do Edit and Continue on a module that was not started in Edit and Continue mode.") },
                    { HResult.CORDBG_E_SET_IP_NOT_ALLOWED_ON_EXCEPTION, (nameof(HResult.CORDBG_E_SET_IP_NOT_ALLOWED_ON_EXCEPTION), "SetIP cannot be done on any exception.") },
                    { HResult.CORDBG_E_VARIABLE_IS_ACTUALLY_LITERAL, (nameof(HResult.CORDBG_E_VARIABLE_IS_ACTUALLY_LITERAL), "The 'variable' does not exist because it is a literal optimized away by the compiler.") },
                    { HResult.CORDBG_E_PROCESS_DETACHED, (nameof(HResult.CORDBG_E_PROCESS_DETACHED), "Process has been detached.") },
                    { HResult.CORDBG_E_ENC_CANT_ADD_FIELD_TO_VALUE_OR_LAYOUT_CLASS, (nameof(HResult.CORDBG_E_ENC_CANT_ADD_FIELD_TO_VALUE_OR_LAYOUT_CLASS), "Adding a field to a value or layout class is prohibited.") },
                    { HResult.CORDBG_E_FIELD_NOT_STATIC, (nameof(HResult.CORDBG_E_FIELD_NOT_STATIC), "GetStaticFieldValue called on a non-static field.") },
                    { HResult.CORDBG_E_FIELD_NOT_INSTANCE, (nameof(HResult.CORDBG_E_FIELD_NOT_INSTANCE), "Returned if someone tries to call GetStaticFieldValue on a non-instance field.") },
                    { HResult.CORDBG_E_ENC_JIT_CANT_UPDATE, (nameof(HResult.CORDBG_E_ENC_JIT_CANT_UPDATE), "The JIT is unable to update the method.") },
                    { HResult.CORDBG_E_ENC_INTERNAL_ERROR, (nameof(HResult.CORDBG_E_ENC_INTERNAL_ERROR), "Internal Runtime Error while doing Edit-and-Continue.") },
                    { HResult.CORDBG_E_ENC_HANGING_FIELD, (nameof(HResult.CORDBG_E_ENC_HANGING_FIELD), "The field was added via Edit and Continue after the class was loaded.") },
                    { HResult.CORDBG_E_MODULE_NOT_LOADED, (nameof(HResult.CORDBG_E_MODULE_NOT_LOADED), "Module not loaded.") },
                    { HResult.CORDBG_E_UNABLE_TO_SET_BREAKPOINT, (nameof(HResult.CORDBG_E_UNABLE_TO_SET_BREAKPOINT), "Cannot set a breakpoint here.") },
                    { HResult.CORDBG_E_DEBUGGING_NOT_POSSIBLE, (nameof(HResult.CORDBG_E_DEBUGGING_NOT_POSSIBLE), "Debugging is not possible due to an incompatibility within the CLR implementation.") },
                    { HResult.CORDBG_E_KERNEL_DEBUGGER_ENABLED, (nameof(HResult.CORDBG_E_KERNEL_DEBUGGER_ENABLED), "A kernel debugger is enabled on the system.  User-mode debugging will trap to the kernel debugger.") },
                    { HResult.CORDBG_E_KERNEL_DEBUGGER_PRESENT, (nameof(HResult.CORDBG_E_KERNEL_DEBUGGER_PRESENT), "A kernel debugger is present on the system.  User-mode debugging will trap to the kernel debugger.") },
                    { HResult.CORDBG_E_INCOMPATIBLE_PROTOCOL, (nameof(HResult.CORDBG_E_INCOMPATIBLE_PROTOCOL), "The debugger's protocol is incompatible with the debuggee.") },
                    { HResult.CORDBG_E_TOO_MANY_PROCESSES, (nameof(HResult.CORDBG_E_TOO_MANY_PROCESSES), "The debugger can only handle a finite number of debuggees.") },
                    { HResult.CORDBG_E_INTEROP_NOT_SUPPORTED, (nameof(HResult.CORDBG_E_INTEROP_NOT_SUPPORTED), "Interop debugging is not supported.") },
                    { HResult.CORDBG_E_NO_REMAP_BREAKPIONT, (nameof(HResult.CORDBG_E_NO_REMAP_BREAKPIONT), "Cannot call RemapFunction until have received RemapBreakpoint.") },
                    { HResult.CORDBG_E_OBJECT_NEUTERED, (nameof(HResult.CORDBG_E_OBJECT_NEUTERED), "Object is in a zombie state.") },
                    { HResult.CORPROF_E_FUNCTION_NOT_COMPILED, (nameof(HResult.CORPROF_E_FUNCTION_NOT_COMPILED), "Function not yet compiled.") },
                    { HResult.CORPROF_E_DATAINCOMPLETE, (nameof(HResult.CORPROF_E_DATAINCOMPLETE), "The ID is not fully loaded/defined yet.") },
                    { HResult.CORPROF_E_FUNCTION_NOT_IL, (nameof(HResult.CORPROF_E_FUNCTION_NOT_IL), "The Method has no associated IL.") },
                    { HResult.CORPROF_E_NOT_MANAGED_THREAD, (nameof(HResult.CORPROF_E_NOT_MANAGED_THREAD), "The thread has never run managed code before.") },
                    { HResult.CORPROF_E_CALL_ONLY_FROM_INIT, (nameof(HResult.CORPROF_E_CALL_ONLY_FROM_INIT), "The function may only be called during profiler initialization.") },
                    { HResult.CORPROF_E_NOT_YET_AVAILABLE, (nameof(HResult.CORPROF_E_NOT_YET_AVAILABLE), "Requested information is not yet available.") },
                    { HResult.CORPROF_E_TYPE_IS_PARAMETERIZED, (nameof(HResult.CORPROF_E_TYPE_IS_PARAMETERIZED), "The given type is a generic and cannot be used with this method.") },
                    { HResult.CORPROF_E_FUNCTION_IS_PARAMETERIZED, (nameof(HResult.CORPROF_E_FUNCTION_IS_PARAMETERIZED), "The given function is a generic and cannot be used with this method.") },
                    { HResult.CORPROF_E_STACKSNAPSHOT_INVALID_TGT_THREAD, (nameof(HResult.CORPROF_E_STACKSNAPSHOT_INVALID_TGT_THREAD), "A profiler tried to walk the stack of an invalid thread") },
                    { HResult.CORPROF_E_STACKSNAPSHOT_UNMANAGED_CTX, (nameof(HResult.CORPROF_E_STACKSNAPSHOT_UNMANAGED_CTX), "A profiler can not walk a thread that is currently executing unmanaged code") },
                    { HResult.CORPROF_E_STACKSNAPSHOT_UNSAFE, (nameof(HResult.CORPROF_E_STACKSNAPSHOT_UNSAFE), "A stackwalk at this point may cause dead locks or data corruption") },
                    { HResult.CORPROF_E_STACKSNAPSHOT_ABORTED, (nameof(HResult.CORPROF_E_STACKSNAPSHOT_ABORTED), "Stackwalking callback requested the walk to abort") },
                    { HResult.CORPROF_E_LITERALS_HAVE_NO_ADDRESS, (nameof(HResult.CORPROF_E_LITERALS_HAVE_NO_ADDRESS), "Returned when asked for the address of a static that is a literal.") },
                    { HResult.CORPROF_E_UNSUPPORTED_CALL_SEQUENCE, (nameof(HResult.CORPROF_E_UNSUPPORTED_CALL_SEQUENCE), "A call was made at an unsupported time.  Examples include illegally calling a profiling API method asynchronously, calling a method that might trigger a GC at an unsafe time, and calling a method at a time that could cause locks to be taken out of order.") },
                    { HResult.CORPROF_E_ASYNCHRONOUS_UNSAFE, (nameof(HResult.CORPROF_E_ASYNCHRONOUS_UNSAFE), "A legal asynchronous call was made at an unsafe time (e.g., CLR locks are held)") },
                    { HResult.CORPROF_E_CLASSID_IS_ARRAY, (nameof(HResult.CORPROF_E_CLASSID_IS_ARRAY), "The specified ClassID cannot be inspected by this function because it is an array") },
                    { HResult.CORPROF_E_CLASSID_IS_COMPOSITE, (nameof(HResult.CORPROF_E_CLASSID_IS_COMPOSITE), "The specified ClassID is a non-array composite type (e.g., ref) and cannot be inspected") },
                    { HResult.CORPROF_E_PROFILER_DETACHING, (nameof(HResult.CORPROF_E_PROFILER_DETACHING), "The profiler's call into the CLR is disallowed because the profiler is attempting to detach.") },
                    { HResult.CORPROF_E_PROFILER_NOT_ATTACHABLE, (nameof(HResult.CORPROF_E_PROFILER_NOT_ATTACHABLE), "The profiler does not support attaching to a live process.") },
                    { HResult.CORPROF_E_UNRECOGNIZED_PIPE_MSG_FORMAT, (nameof(HResult.CORPROF_E_UNRECOGNIZED_PIPE_MSG_FORMAT), "The message sent on the profiling API attach pipe is in an unrecognized format.") },
                    { HResult.CORPROF_E_PROFILER_ALREADY_ACTIVE, (nameof(HResult.CORPROF_E_PROFILER_ALREADY_ACTIVE), "The request to attach a profiler was denied because a profiler is already loaded.") },
                    { HResult.CORPROF_E_PROFILEE_INCOMPATIBLE_WITH_TRIGGER, (nameof(HResult.CORPROF_E_PROFILEE_INCOMPATIBLE_WITH_TRIGGER), "Unable to request a profiler attach because the target profilee's runtime is of a version incompatible with the current process calling AttachProfiler().") },
                    { HResult.CORPROF_E_IPC_FAILED, (nameof(HResult.CORPROF_E_IPC_FAILED), "AttachProfiler() encountered an error while communicating on the pipe to the target profilee.  This is often caused by a target profilee that is shutting down or killed while AttachProfiler() is reading or writing the pipe.") },
                    { HResult.CORPROF_E_PROFILEE_PROCESS_NOT_FOUND, (nameof(HResult.CORPROF_E_PROFILEE_PROCESS_NOT_FOUND), "AttachProfiler() was unable to find a profilee with the specified process ID.") },
                    { HResult.CORPROF_E_CALLBACK3_REQUIRED, (nameof(HResult.CORPROF_E_CALLBACK3_REQUIRED), "Profiler must implement ICorProfilerCallback3 interface for this call to be supported.") },
                    { HResult.CORPROF_E_UNSUPPORTED_FOR_ATTACHING_PROFILER, (nameof(HResult.CORPROF_E_UNSUPPORTED_FOR_ATTACHING_PROFILER), "This call was attempted by a profiler that attached to the process after startup, but this call is only supported by profilers that are loaded into the process on startup.") },
                    { HResult.CORPROF_E_IRREVERSIBLE_INSTRUMENTATION_PRESENT, (nameof(HResult.CORPROF_E_IRREVERSIBLE_INSTRUMENTATION_PRESENT), "Detach is impossible because the profiler has either instrumented IL or inserted enter/leave hooks. Detach was not attempted; the profiler is still fully attached.") },
                    { HResult.CORPROF_E_RUNTIME_UNINITIALIZED, (nameof(HResult.CORPROF_E_RUNTIME_UNINITIALIZED), "The profiler called a function that cannot complete because the CLR is not yet fully initialized.  The profiler may try again once the CLR has fully started.") },
                    { HResult.CORPROF_E_IMMUTABLE_FLAGS_SET, (nameof(HResult.CORPROF_E_IMMUTABLE_FLAGS_SET), "Detach is impossible because immutable flags were set by the profiler at startup. Detach was not attempted; the profiler is still fully attached.") },
                    { HResult.CORPROF_E_PROFILER_NOT_YET_INITIALIZED, (nameof(HResult.CORPROF_E_PROFILER_NOT_YET_INITIALIZED), "The profiler called a function that cannot complete because the profiler is not yet fully initialized.") },
                    { HResult.CORPROF_E_INCONSISTENT_WITH_FLAGS, (nameof(HResult.CORPROF_E_INCONSISTENT_WITH_FLAGS), "The profiler called a function that first requires additional flags to be set in the event mask.  This HRESULT may also indicate that the profiler called a function that first requires that some of the flags currently set in the event mask be reset.") },
                    { HResult.CORPROF_E_PROFILER_CANCEL_ACTIVATION, (nameof(HResult.CORPROF_E_PROFILER_CANCEL_ACTIVATION), "The profiler has requested that the CLR instance not load the profiler into this process.") },
                    { HResult.CORPROF_E_CONCURRENT_GC_NOT_PROFILABLE, (nameof(HResult.CORPROF_E_CONCURRENT_GC_NOT_PROFILABLE), "Concurrent GC mode is enabled, which prevents use of COR_PRF_MONITOR_GC") },
                    { HResult.CORPROF_E_DEBUGGING_DISABLED, (nameof(HResult.CORPROF_E_DEBUGGING_DISABLED), "This functionality requires CoreCLR debugging to be enabled.") },
                    { HResult.CORPROF_E_TIMEOUT_WAITING_FOR_CONCURRENT_GC, (nameof(HResult.CORPROF_E_TIMEOUT_WAITING_FOR_CONCURRENT_GC), "Timed out on waiting for concurrent GC to finish during attach.") },
                    { HResult.CORPROF_E_MODULE_IS_DYNAMIC, (nameof(HResult.CORPROF_E_MODULE_IS_DYNAMIC), "The specified module was dynamically generated (e.g., via Reflection.Emit API), and is thus not supported by this API method.") },
                    { HResult.CORPROF_E_CALLBACK4_REQUIRED, (nameof(HResult.CORPROF_E_CALLBACK4_REQUIRED), "Profiler must implement ICorProfilerCallback4 interface for this call to be supported.") },
                    { HResult.CORPROF_E_REJIT_NOT_ENABLED, (nameof(HResult.CORPROF_E_REJIT_NOT_ENABLED), "This call is not supported unless ReJIT is first enabled during initialization by setting COR_PRF_ENABLE_REJIT via SetEventMask.") },
                    { HResult.CORPROF_E_FUNCTION_IS_COLLECTIBLE, (nameof(HResult.CORPROF_E_FUNCTION_IS_COLLECTIBLE), "The specified function is instantiated into a collectible assembly, and is thus not supported by this API method.") },
                    { HResult.CORPROF_E_CALLBACK6_REQUIRED, (nameof(HResult.CORPROF_E_CALLBACK6_REQUIRED), "Profiler must implement ICorProfilerCallback6 interface for this call to be supported.") },
                    { HResult.CORPROF_E_CALLBACK7_REQUIRED, (nameof(HResult.CORPROF_E_CALLBACK7_REQUIRED), "Profiler must implement ICorProfilerCallback7 interface for this call to be supported.") },
                    { HResult.CORPROF_E_REJIT_INLINING_DISABLED, (nameof(HResult.CORPROF_E_REJIT_INLINING_DISABLED), "The runtime's tracking of inlined methods for ReJIT is not enabled.") },
                    { HResult.CORDIAGIPC_E_BAD_ENCODING, (nameof(HResult.CORDIAGIPC_E_BAD_ENCODING), "The runtime was unable to decode the Header or Payload.") },
                    { HResult.CORDIAGIPC_E_UNKNOWN_COMMAND, (nameof(HResult.CORDIAGIPC_E_UNKNOWN_COMMAND), "The specified CommandSet or CommandId is unknown.") },
                    { HResult.CORDIAGIPC_E_UNKNOWN_MAGIC, (nameof(HResult.CORDIAGIPC_E_UNKNOWN_MAGIC), "The magic version of Diagnostics IPC is unknown.") },
                    { HResult.CORDIAGIPC_E_UNKNOWN_ERROR, (nameof(HResult.CORDIAGIPC_E_UNKNOWN_ERROR), "An unknown error occurred in the Diagnpostics IPC Server.") },
                    { HResult.CORPROF_E_SUSPENSION_IN_PROGRESS, (nameof(HResult.CORPROF_E_SUSPENSION_IN_PROGRESS), "The runtime cannot be suspened since a suspension is already in progress.") },
                    { HResult.SECURITY_E_INCOMPATIBLE_SHARE, (nameof(HResult.SECURITY_E_INCOMPATIBLE_SHARE), "Loading this assembly would produce a different grant set from other instances.") },
                    { HResult.SECURITY_E_UNVERIFIABLE, (nameof(HResult.SECURITY_E_UNVERIFIABLE), "Unverifiable code failed policy check.") },
                    { HResult.SECURITY_E_INCOMPATIBLE_EVIDENCE, (nameof(HResult.SECURITY_E_INCOMPATIBLE_EVIDENCE), "Assembly already loaded without additional security evidence.") },
                    { HResult.CORSEC_E_POLICY_EXCEPTION, (nameof(HResult.CORSEC_E_POLICY_EXCEPTION), "PolicyException thrown.") },
                    { HResult.CORSEC_E_MIN_GRANT_FAIL, (nameof(HResult.CORSEC_E_MIN_GRANT_FAIL), "Failed to grant minimum permission requests.") },
                    { HResult.CORSEC_E_NO_EXEC_PERM, (nameof(HResult.CORSEC_E_NO_EXEC_PERM), "Failed to grant permission to execute.") },
                    { HResult.CORSEC_E_XMLSYNTAX, (nameof(HResult.CORSEC_E_XMLSYNTAX), "XML Syntax error.") },
                    { HResult.CORSEC_E_INVALID_STRONGNAME, (nameof(HResult.CORSEC_E_INVALID_STRONGNAME), "Strong name validation failed.") },
                    { HResult.CORSEC_E_MISSING_STRONGNAME, (nameof(HResult.CORSEC_E_MISSING_STRONGNAME), "Assembly is not strong named.") },
                    { HResult.CORSEC_E_INVALID_IMAGE_FORMAT, (nameof(HResult.CORSEC_E_INVALID_IMAGE_FORMAT), "Invalid assembly file format.") },
                    { HResult.CORSEC_E_INVALID_PUBLICKEY, (nameof(HResult.CORSEC_E_INVALID_PUBLICKEY), "Invalid assembly public key.") },
                    { HResult.CORSEC_E_SIGNATURE_MISMATCH, (nameof(HResult.CORSEC_E_SIGNATURE_MISMATCH), "Signature size mismatch.") },
                    { HResult.CORSEC_E_CRYPTO, (nameof(HResult.CORSEC_E_CRYPTO), "Failure during Cryptographic operation.") },
                    { HResult.CORSEC_E_CRYPTO_UNEX_OPER, (nameof(HResult.CORSEC_E_CRYPTO_UNEX_OPER), "Unexpected Cryptographic operation.") },
                    { HResult.CORSECATTR_E_BAD_ACTION, (nameof(HResult.CORSECATTR_E_BAD_ACTION), "Invalid security action code.") },
                    { HResult.COR_E_EXCEPTION, (nameof(HResult.COR_E_EXCEPTION), "General Exception") },
                    { HResult.COR_E_SYSTEM, (nameof(HResult.COR_E_SYSTEM), "System.Exception") },
                    { HResult.COR_E_ARGUMENTOUTOFRANGE, (nameof(HResult.COR_E_ARGUMENTOUTOFRANGE), "An argument was out of its legal range.") },
                    { HResult.COR_E_ARRAYTYPEMISMATCH, (nameof(HResult.COR_E_ARRAYTYPEMISMATCH), "Attempted to store an object of the wrong type in an array.") },
                    { HResult.COR_E_CONTEXTMARSHAL, (nameof(HResult.COR_E_CONTEXTMARSHAL), "Attempted to marshal an object across a context boundary.") },
                    { HResult.COR_E_TIMEOUT, (nameof(HResult.COR_E_TIMEOUT), "Operation timed out.") },
                    { HResult.COR_E_EXECUTIONENGINE, (nameof(HResult.COR_E_EXECUTIONENGINE), "Internal CLR error.") },
                    { HResult.COR_E_FIELDACCESS, (nameof(HResult.COR_E_FIELDACCESS), "Access to this field is denied.") },
                    { HResult.COR_E_INDEXOUTOFRANGE, (nameof(HResult.COR_E_INDEXOUTOFRANGE), "Array subscript out of range.") },
                    { HResult.COR_E_INVALIDOPERATION, (nameof(HResult.COR_E_INVALIDOPERATION), "An operation is not legal in the current state.") },
                    { HResult.COR_E_SECURITY, (nameof(HResult.COR_E_SECURITY), "An error relating to security occurred.") },
                    { HResult.COR_E_SERIALIZATION, (nameof(HResult.COR_E_SERIALIZATION), "An error relating to serialization occurred.") },
                    { HResult.COR_E_VERIFICATION, (nameof(HResult.COR_E_VERIFICATION), "A verification failure has occurred.") },
                    { HResult.COR_E_METHODACCESS, (nameof(HResult.COR_E_METHODACCESS), "Access to this method is denied.") },
                    { HResult.COR_E_MISSINGFIELD, (nameof(HResult.COR_E_MISSINGFIELD), "Field does not exist.") },
                    { HResult.COR_E_MISSINGMEMBER, (nameof(HResult.COR_E_MISSINGMEMBER), "Member does not exist.") },
                    { HResult.COR_E_MISSINGMETHOD, (nameof(HResult.COR_E_MISSINGMETHOD), "Method does not exist.") },
                    { HResult.COR_E_MULTICASTNOTSUPPORTED, (nameof(HResult.COR_E_MULTICASTNOTSUPPORTED), "Attempt to combine delegates that are not multicast.") },
                    { HResult.COR_E_NOTSUPPORTED, (nameof(HResult.COR_E_NOTSUPPORTED), "Operation is not supported.") },
                    { HResult.COR_E_OVERFLOW, (nameof(HResult.COR_E_OVERFLOW), "Arithmetic, casting or conversion operation overflowed or underflowed.") },
                    { HResult.COR_E_RANK, (nameof(HResult.COR_E_RANK), "An array has the wrong number of dimensions for a particular operation.") },
                    { HResult.COR_E_SYNCHRONIZATIONLOCK, (nameof(HResult.COR_E_SYNCHRONIZATIONLOCK), "This operation must be called from a synchronized block.") },
                    { HResult.COR_E_THREADINTERRUPTED, (nameof(HResult.COR_E_THREADINTERRUPTED), "Thread was interrupted from a waiting state.") },
                    { HResult.COR_E_MEMBERACCESS, (nameof(HResult.COR_E_MEMBERACCESS), "Access to this member is denied.") },
                    { HResult.COR_E_THREADSTATE, (nameof(HResult.COR_E_THREADSTATE), "Thread is in an invalid state for this operation.") },
                    { HResult.COR_E_THREADSTOP, (nameof(HResult.COR_E_THREADSTOP), "Thread is stopping.") },
                    { HResult.COR_E_TYPELOAD, (nameof(HResult.COR_E_TYPELOAD), "Could not find or load a type.") },
                    { HResult.COR_E_ENTRYPOINTNOTFOUND, (nameof(HResult.COR_E_ENTRYPOINTNOTFOUND), "Could not find the specified DllImport entrypoint.") },
                    { HResult.COR_E_DLLNOTFOUND, (nameof(HResult.COR_E_DLLNOTFOUND), "Could not find the specified DllImport Dll.") },
                    { HResult.COR_E_THREADSTART, (nameof(HResult.COR_E_THREADSTART), "Indicate that a user thread fails to start.") },
                    { HResult.COR_E_INVALIDCOMOBJECT, (nameof(HResult.COR_E_INVALIDCOMOBJECT), "An invalid __ComObject has been used.") },
                    { HResult.COR_E_NOTFINITENUMBER, (nameof(HResult.COR_E_NOTFINITENUMBER), "Not a Number.") },
                    { HResult.COR_E_DUPLICATEWAITOBJECT, (nameof(HResult.COR_E_DUPLICATEWAITOBJECT), "An object appears more than once in the wait objects array.") },
                    { HResult.COR_E_SEMAPHOREFULL, (nameof(HResult.COR_E_SEMAPHOREFULL), "Reached maximum count for semaphore.") },
                    { HResult.COR_E_WAITHANDLECANNOTBEOPENED, (nameof(HResult.COR_E_WAITHANDLECANNOTBEOPENED), "No semaphore of the given name exists.") },
                    { HResult.COR_E_ABANDONEDMUTEX, (nameof(HResult.COR_E_ABANDONEDMUTEX), "The wait completed due to an abandoned mutex.") },
                    { HResult.COR_E_THREADABORTED, (nameof(HResult.COR_E_THREADABORTED), "Thread has aborted.") },
                    { HResult.COR_E_INVALIDOLEVARIANTTYPE, (nameof(HResult.COR_E_INVALIDOLEVARIANTTYPE), "OLE Variant has an invalid type.") },
                    { HResult.COR_E_MISSINGMANIFESTRESOURCE, (nameof(HResult.COR_E_MISSINGMANIFESTRESOURCE), "An expected resource in the assembly manifest was missing.") },
                    { HResult.COR_E_SAFEARRAYTYPEMISMATCH, (nameof(HResult.COR_E_SAFEARRAYTYPEMISMATCH), "A mismatch has occurred between the runtime type of the array and the sub type recorded in the metadata.") },
                    { HResult.COR_E_TYPEINITIALIZATION, (nameof(HResult.COR_E_TYPEINITIALIZATION), "Uncaught exception during type initialization.") },
                    { HResult.COR_E_MARSHALDIRECTIVE, (nameof(HResult.COR_E_MARSHALDIRECTIVE), "Invalid marshaling directives.") },
                    { HResult.COR_E_MISSINGSATELLITEASSEMBLY, (nameof(HResult.COR_E_MISSINGSATELLITEASSEMBLY), "An expected satellite assembly containing the ultimate fallback resources for a given culture was not found or could not be loaded.") },
                    { HResult.COR_E_FORMAT, (nameof(HResult.COR_E_FORMAT), "The format of one argument does not meet the contract of the method.") },
                    { HResult.COR_E_SAFEARRAYRANKMISMATCH, (nameof(HResult.COR_E_SAFEARRAYRANKMISMATCH), "A mismatch has occurred between the runtime rank of the array and the rank recorded in the metadata.") },
                    { HResult.COR_E_PLATFORMNOTSUPPORTED, (nameof(HResult.COR_E_PLATFORMNOTSUPPORTED), "Operation is not supported on this platform.") },
                    { HResult.COR_E_INVALIDPROGRAM, (nameof(HResult.COR_E_INVALIDPROGRAM), "Invalid IL or CLR metadata.") },
                    { HResult.COR_E_OPERATIONCANCELED, (nameof(HResult.COR_E_OPERATIONCANCELED), "The operation was cancelled.") },
                    { HResult.COR_E_INSUFFICIENTMEMORY, (nameof(HResult.COR_E_INSUFFICIENTMEMORY), "Not enough memory was available for an operation.") },
                    { HResult.COR_E_RUNTIMEWRAPPED, (nameof(HResult.COR_E_RUNTIMEWRAPPED), "An object that does not derive from System.Exception has been wrapped in a RuntimeWrappedException.") },
                    { HResult.COR_E_DATAMISALIGNED, (nameof(HResult.COR_E_DATAMISALIGNED), "A datatype misalignment was detected in a load or store instruction.") },
                    { HResult.COR_E_CODECONTRACTFAILED, (nameof(HResult.COR_E_CODECONTRACTFAILED), "A managed code contract (ie, precondition, postcondition, invariant, or assert) failed.") },
                    { HResult.COR_E_TYPEACCESS, (nameof(HResult.COR_E_TYPEACCESS), "Access to this type is denied.") },
                    { HResult.COR_E_ACCESSING_CCW, (nameof(HResult.COR_E_ACCESSING_CCW), "Fail to access a CCW because the corresponding managed object is already collected.") },
                    { HResult.COR_E_KEYNOTFOUND, (nameof(HResult.COR_E_KEYNOTFOUND), "The given key was not present in the dictionary.") },
                    { HResult.COR_E_INSUFFICIENTEXECUTIONSTACK, (nameof(HResult.COR_E_INSUFFICIENTEXECUTIONSTACK), "Insufficient stack to continue executing the program safely. This can happen from having too many functions on the call stack or function on the stack using too much stack space.") },
                    { HResult.COR_E_APPLICATION, (nameof(HResult.COR_E_APPLICATION), "Application exception") },
                    { HResult.COR_E_INVALIDFILTERCRITERIA, (nameof(HResult.COR_E_INVALIDFILTERCRITERIA), "The given filter criteria does not match the filter content.") },
                    { HResult.COR_E_REFLECTIONTYPELOAD, (nameof(HResult.COR_E_REFLECTIONTYPELOAD), "Could not find or load a specific class that was requested through Reflection.") },
                    { HResult.COR_E_TARGET, (nameof(HResult.COR_E_TARGET), "Attempt to invoke non-static method with a null Object.") },
                    { HResult.COR_E_TARGETINVOCATION, (nameof(HResult.COR_E_TARGETINVOCATION), "Uncaught exception thrown by method called through Reflection.") },
                    { HResult.COR_E_CUSTOMATTRIBUTEFORMAT, (nameof(HResult.COR_E_CUSTOMATTRIBUTEFORMAT), "Custom attribute has invalid format.") },
                    { HResult.COR_E_IO, (nameof(HResult.COR_E_IO), "Error during managed I/O.") },
                    { HResult.COR_E_FILELOAD, (nameof(HResult.COR_E_FILELOAD), "Could not find or load a specific file.") },
                    { HResult.COR_E_OBJECTDISPOSED, (nameof(HResult.COR_E_OBJECTDISPOSED), "The object has already been disposed.") },
                    { HResult.COR_E_FAILFAST, (nameof(HResult.COR_E_FAILFAST), "Runtime operation halted by call to System.Environment.FailFast().") },
                    { HResult.COR_E_HOSTPROTECTION, (nameof(HResult.COR_E_HOSTPROTECTION), "The host has forbidden this operation.") },
                    { HResult.COR_E_ILLEGAL_REENTRANCY, (nameof(HResult.COR_E_ILLEGAL_REENTRANCY), "Attempted to call into managed code when executing inside a low level extensibility point.") },
                    { HResult.CLR_E_SHIM_RUNTIMELOAD, (nameof(HResult.CLR_E_SHIM_RUNTIMELOAD), "Failed to load the runtime.") },
                    { HResult.CLR_E_SHIM_LEGACYRUNTIMEALREADYBOUND, (nameof(HResult.CLR_E_SHIM_LEGACYRUNTIMEALREADYBOUND), "A runtime has already been bound for legacy activation policy use.") },
                    { HResult.VER_E_FIELD_SIG, (nameof(HResult.VER_E_FIELD_SIG), "[field sig]") },
                    { HResult.VER_E_CIRCULAR_VAR_CONSTRAINTS, (nameof(HResult.VER_E_CIRCULAR_VAR_CONSTRAINTS), "Method parent has circular class type parameter constraints.") },
                    { HResult.VER_E_CIRCULAR_MVAR_CONSTRAINTS, (nameof(HResult.VER_E_CIRCULAR_MVAR_CONSTRAINTS), "Method has circular method type parameter constraints.") },
                    { HResult.VER_E_CIRCULAR_MVAR_CONSTRAINTS, (nameof(HResult.VER_E_CIRCULAR_MVAR_CONSTRAINTS), "Method has circular method type parameter constraints.") },
                    { HResult.VLDTR_E_SIG_BADVOID, (nameof(HResult.VLDTR_E_SIG_BADVOID), "Illegal 'void' in signature.") },
                    { HResult.VLDTR_E_GP_ILLEGAL_VARIANT_MVAR, (nameof(HResult.VLDTR_E_GP_ILLEGAL_VARIANT_MVAR), "GenericParam is a method type parameter and must be non-variant.") },
                    { HResult.CORDBG_E_THREAD_NOT_SCHEDULED, (nameof(HResult.CORDBG_E_THREAD_NOT_SCHEDULED), "Thread is not scheduled. Thus we may not have OSThreadId, handle, or context.") },
                    { HResult.CORDBG_E_HANDLE_HAS_BEEN_DISPOSED, (nameof(HResult.CORDBG_E_HANDLE_HAS_BEEN_DISPOSED), "Handle has been disposed.") },
                    { HResult.CORDBG_E_NONINTERCEPTABLE_EXCEPTION, (nameof(HResult.CORDBG_E_NONINTERCEPTABLE_EXCEPTION), "Cannot intercept this exception.") },
                    { HResult.CORDBG_E_INTERCEPT_FRAME_ALREADY_SET, (nameof(HResult.CORDBG_E_INTERCEPT_FRAME_ALREADY_SET), "The intercept frame for this exception has already been set.") },
                    { HResult.CORDBG_E_NO_NATIVE_PATCH_AT_ADDR, (nameof(HResult.CORDBG_E_NO_NATIVE_PATCH_AT_ADDR), "There is no native patch at the given address.") },
                    { HResult.CORDBG_E_MUST_BE_INTEROP_DEBUGGING, (nameof(HResult.CORDBG_E_MUST_BE_INTEROP_DEBUGGING), "This API is only allowed when interop debugging.") },
                    { HResult.CORDBG_E_NATIVE_PATCH_ALREADY_AT_ADDR, (nameof(HResult.CORDBG_E_NATIVE_PATCH_ALREADY_AT_ADDR), "There is already a native patch at the address.") },
                    { HResult.CORDBG_E_TIMEOUT, (nameof(HResult.CORDBG_E_TIMEOUT), "A wait timed out, likely an indication of deadlock.") },
                    { HResult.CORDBG_E_CANT_CALL_ON_THIS_THREAD, (nameof(HResult.CORDBG_E_CANT_CALL_ON_THIS_THREAD), "Cannot use the API on this thread.") },
                    { HResult.CORDBG_E_ENC_INFOLESS_METHOD, (nameof(HResult.CORDBG_E_ENC_INFOLESS_METHOD), "Method was not JIT'd in EnC mode.") },
                    { HResult.CORDBG_E_ENC_IN_FUNCLET, (nameof(HResult.CORDBG_E_ENC_IN_FUNCLET), "Method is in a callable handler/filter. Cannot increase stack.") },
                    { HResult.CORDBG_E_ENC_EDIT_NOT_SUPPORTED, (nameof(HResult.CORDBG_E_ENC_EDIT_NOT_SUPPORTED), "Attempt to perform unsupported edit.") },
                    { HResult.CORDBG_E_NOTREADY, (nameof(HResult.CORDBG_E_NOTREADY), "The LS is not in a good spot to perform the requested operation.") },
                    { HResult.CORDBG_E_CANNOT_RESOLVE_ASSEMBLY, (nameof(HResult.CORDBG_E_CANNOT_RESOLVE_ASSEMBLY), "We failed to resolve assembly given an AssemblyRef token. Assembly may be not loaded yet or not a valid token.") },
                    { HResult.CORDBG_E_MUST_BE_IN_LOAD_MODULE, (nameof(HResult.CORDBG_E_MUST_BE_IN_LOAD_MODULE), "Must be in context of LoadModule callback to perform requested operation.") },
                    { HResult.CORDBG_E_CANNOT_BE_ON_ATTACH, (nameof(HResult.CORDBG_E_CANNOT_BE_ON_ATTACH), "Requested operation cannot be performed during an attach operation.") },
                    { HResult.CORDBG_E_NGEN_NOT_SUPPORTED, (nameof(HResult.CORDBG_E_NGEN_NOT_SUPPORTED), "NGEN must be supported to perform the requested operation.") },
                    { HResult.CORDBG_E_ILLEGAL_SHUTDOWN_ORDER, (nameof(HResult.CORDBG_E_ILLEGAL_SHUTDOWN_ORDER), "Trying to shutdown out of order.") },
                    { HResult.CORDBG_E_CANNOT_DEBUG_FIBER_PROCESS, (nameof(HResult.CORDBG_E_CANNOT_DEBUG_FIBER_PROCESS), "Debugging fiber mode managed process is not supported.") },
                    { HResult.CORDBG_E_MUST_BE_IN_CREATE_PROCESS, (nameof(HResult.CORDBG_E_MUST_BE_IN_CREATE_PROCESS), "Must be in context of CreateProcess callback to perform requested operation.") },
                    { HResult.CORDBG_E_DETACH_FAILED_OUTSTANDING_EVALS, (nameof(HResult.CORDBG_E_DETACH_FAILED_OUTSTANDING_EVALS), "All outstanding func-evals have not completed, detaching is not allowed at this time.") },
                    { HResult.CORDBG_E_DETACH_FAILED_OUTSTANDING_STEPPERS, (nameof(HResult.CORDBG_E_DETACH_FAILED_OUTSTANDING_STEPPERS), "All outstanding steppers have not been closed, detaching is not allowed at this time.") },
                    { HResult.CORDBG_E_CANT_INTEROP_STEP_OUT, (nameof(HResult.CORDBG_E_CANT_INTEROP_STEP_OUT), "Cannot have an ICorDebugStepper do a native step-out.") },
                    { HResult.CORDBG_E_DETACH_FAILED_OUTSTANDING_BREAKPOINTS, (nameof(HResult.CORDBG_E_DETACH_FAILED_OUTSTANDING_BREAKPOINTS), "All outstanding breakpoints have not been closed, detaching is not allowed at this time.") },
                    { HResult.CORDBG_E_ILLEGAL_IN_STACK_OVERFLOW, (nameof(HResult.CORDBG_E_ILLEGAL_IN_STACK_OVERFLOW), "The operation is illegal because of a stack overflow.") },
                    { HResult.CORDBG_E_ILLEGAL_AT_GC_UNSAFE_POINT, (nameof(HResult.CORDBG_E_ILLEGAL_AT_GC_UNSAFE_POINT), "The operation failed because it is a GC unsafe point.") },
                    { HResult.CORDBG_E_ILLEGAL_IN_PROLOG, (nameof(HResult.CORDBG_E_ILLEGAL_IN_PROLOG), "The operation failed because the thread is in the prolog.") },
                    { HResult.CORDBG_E_ILLEGAL_IN_NATIVE_CODE, (nameof(HResult.CORDBG_E_ILLEGAL_IN_NATIVE_CODE), "The operation failed because the thread is in native code.") },
                    { HResult.CORDBG_E_ILLEGAL_IN_OPTIMIZED_CODE, (nameof(HResult.CORDBG_E_ILLEGAL_IN_OPTIMIZED_CODE), "The operation failed because the thread is in optimized code.") },
                    { HResult.CORDBG_E_APPDOMAIN_MISMATCH, (nameof(HResult.CORDBG_E_APPDOMAIN_MISMATCH), "A supplied object or type belongs to the wrong AppDomain.") },
                    { HResult.CORDBG_E_CONTEXT_UNVAILABLE, (nameof(HResult.CORDBG_E_CONTEXT_UNVAILABLE), "The thread's context is not available.") },
                    { HResult.CORDBG_E_UNCOMPATIBLE_PLATFORMS, (nameof(HResult.CORDBG_E_UNCOMPATIBLE_PLATFORMS), "The operation failed because debuggee and debugger are on incompatible platforms.") },
                    { HResult.CORDBG_E_DEBUGGING_DISABLED, (nameof(HResult.CORDBG_E_DEBUGGING_DISABLED), "The operation failed because the debugging has been disabled") },
                    { HResult.CORDBG_E_DETACH_FAILED_ON_ENC, (nameof(HResult.CORDBG_E_DETACH_FAILED_ON_ENC), "Detach is illegal after an Edit and Continue on a module.") },
                    { HResult.CORDBG_E_CURRENT_EXCEPTION_IS_OUTSIDE_CURRENT_EXECUTION_SCOPE, (nameof(HResult.CORDBG_E_CURRENT_EXCEPTION_IS_OUTSIDE_CURRENT_EXECUTION_SCOPE), "Cannot intercept the current exception at the specified frame.") },
                    { HResult.CORDBG_E_HELPER_MAY_DEADLOCK, (nameof(HResult.CORDBG_E_HELPER_MAY_DEADLOCK), "The debugger helper thread cannot obtain the locks it needs to perform this operation.") },
                    { HResult.CORDBG_E_MISSING_METADATA, (nameof(HResult.CORDBG_E_MISSING_METADATA), "The operation failed because the debugger could not get the metadata.") },
                    { HResult.CORDBG_E_TARGET_INCONSISTENT, (nameof(HResult.CORDBG_E_TARGET_INCONSISTENT), "The debuggee is in a corrupt state.") },
                    { HResult.CORDBG_E_DETACH_FAILED_OUTSTANDING_TARGET_RESOURCES, (nameof(HResult.CORDBG_E_DETACH_FAILED_OUTSTANDING_TARGET_RESOURCES), "Detach failed because there are outstanding resources in the target.") },
                    { HResult.CORDBG_E_TARGET_READONLY, (nameof(HResult.CORDBG_E_TARGET_READONLY), "The debuggee is read-only.") },
                    { HResult.CORDBG_E_MISMATCHED_CORWKS_AND_DACWKS_DLLS, (nameof(HResult.CORDBG_E_MISMATCHED_CORWKS_AND_DACWKS_DLLS), "The version of clr.dll in the target does not match the one mscordacwks.dll was built for.") },
                    { HResult.CORDBG_E_MODULE_LOADED_FROM_DISK, (nameof(HResult.CORDBG_E_MODULE_LOADED_FROM_DISK), "Symbols are not supplied for modules loaded from disk.") },
                    { HResult.CORDBG_E_SYMBOLS_NOT_AVAILABLE, (nameof(HResult.CORDBG_E_SYMBOLS_NOT_AVAILABLE), "The application did not supply symbols when it loaded or created this module, or they are not yet available.") },
                    { HResult.CORDBG_E_DEBUG_COMPONENT_MISSING, (nameof(HResult.CORDBG_E_DEBUG_COMPONENT_MISSING), "A debug component is not installed.") },
                    { HResult.CORDBG_E_LIBRARY_PROVIDER_ERROR, (nameof(HResult.CORDBG_E_LIBRARY_PROVIDER_ERROR), "The ICLRDebuggingLibraryProvider callback returned an error or did not provide a valid handle.") },
                    { HResult.CORDBG_E_NOT_CLR, (nameof(HResult.CORDBG_E_NOT_CLR), "The module at the base address indicated was not recognized as a CLR") },
                    { HResult.CORDBG_E_MISSING_DATA_TARGET_INTERFACE, (nameof(HResult.CORDBG_E_MISSING_DATA_TARGET_INTERFACE), "The provided data target does not implement the required interfaces for this version of the runtime") },
                    { HResult.CORDBG_E_UNSUPPORTED_DEBUGGING_MODEL, (nameof(HResult.CORDBG_E_UNSUPPORTED_DEBUGGING_MODEL), "This debugging model is unsupported by the specified runtime") },
                    { HResult.CORDBG_E_UNSUPPORTED_FORWARD_COMPAT, (nameof(HResult.CORDBG_E_UNSUPPORTED_FORWARD_COMPAT), "The debugger is not designed to support the version of the CLR the debuggee is using.") },
                    { HResult.CORDBG_E_UNSUPPORTED_VERSION_STRUCT, (nameof(HResult.CORDBG_E_UNSUPPORTED_VERSION_STRUCT), "The version struct has an unrecognized value for wStructVersion") },
                    { HResult.CORDBG_E_READVIRTUAL_FAILURE, (nameof(HResult.CORDBG_E_READVIRTUAL_FAILURE), "A call into a ReadVirtual implementation returned failure") },
                    { HResult.CORDBG_E_VALUE_POINTS_TO_FUNCTION, (nameof(HResult.CORDBG_E_VALUE_POINTS_TO_FUNCTION), "The Debugging API doesn't support dereferencing function pointers.") },
                    { HResult.CORDBG_E_CORRUPT_OBJECT, (nameof(HResult.CORDBG_E_CORRUPT_OBJECT), "The address provided does not point to a valid managed object.") },
                    { HResult.CORDBG_E_GC_STRUCTURES_INVALID, (nameof(HResult.CORDBG_E_GC_STRUCTURES_INVALID), "The GC heap structures are not in a valid state for traversal.") },
                    { HResult.CORDBG_E_INVALID_OPCODE, (nameof(HResult.CORDBG_E_INVALID_OPCODE), "The specified IL offset or opcode is not supported for this operation.") },
                    { HResult.CORDBG_E_UNSUPPORTED, (nameof(HResult.CORDBG_E_UNSUPPORTED), "The specified action is unsupported by this version of the runtime.") },
                    { HResult.CORDBG_E_MISSING_DEBUGGER_EXPORTS, (nameof(HResult.CORDBG_E_MISSING_DEBUGGER_EXPORTS), "The debuggee memory space does not have the expected debugging export table.") },
                    { HResult.CORDBG_E_DATA_TARGET_ERROR, (nameof(HResult.CORDBG_E_DATA_TARGET_ERROR), "Failure when calling a data target method.") },
                    { HResult.CORDBG_E_NO_IMAGE_AVAILABLE, (nameof(HResult.CORDBG_E_NO_IMAGE_AVAILABLE), "Couldn't find a native image.") },
                    { HResult.CORDBG_E_UNSUPPORTED_DELEGATE, (nameof(HResult.CORDBG_E_UNSUPPORTED_DELEGATE), "The delegate contains a delegate currently not supported by the API.") },
                    { HResult.PEFMT_E_64BIT, (nameof(HResult.PEFMT_E_64BIT), "File is PE32+.") },
                    { HResult.PEFMT_E_32BIT, (nameof(HResult.PEFMT_E_32BIT), "File is PE32") },
                    { HResult.NGEN_E_SYS_ASM_NI_MISSING, (nameof(HResult.NGEN_E_SYS_ASM_NI_MISSING), "NGen cannot proceed because Mscorlib.dll does not have a native image") },
                    { HResult.NGEN_E_SYS_ASM_NI_MISSING, (nameof(HResult.NGEN_E_SYS_ASM_NI_MISSING), "NGen cannot proceed because Mscorlib.dll does not have a native image") },
                    { HResult.CLR_E_BIND_ASSEMBLY_VERSION_TOO_LOW, (nameof(HResult.CLR_E_BIND_ASSEMBLY_VERSION_TOO_LOW), "The bound assembly has a version that is lower than that of the request.") },
                    { HResult.CLR_E_BIND_ASSEMBLY_PUBLIC_KEY_MISMATCH, (nameof(HResult.CLR_E_BIND_ASSEMBLY_PUBLIC_KEY_MISMATCH), "The assembly version has a public key token that does not match that of the request.") },
                    { HResult.CLR_E_BIND_IMAGE_UNAVAILABLE, (nameof(HResult.CLR_E_BIND_IMAGE_UNAVAILABLE), "The requested image was not found or is unavailable.") },
                    { HResult.CLR_E_BIND_UNRECOGNIZED_IDENTITY_FORMAT, (nameof(HResult.CLR_E_BIND_UNRECOGNIZED_IDENTITY_FORMAT), "The provided identity format is not recognized.") },
                    { HResult.CLR_E_BIND_ASSEMBLY_NOT_FOUND, (nameof(HResult.CLR_E_BIND_ASSEMBLY_NOT_FOUND), "A binding for the specified assembly name was not found.") },
                    { HResult.CLR_E_BIND_TYPE_NOT_FOUND, (nameof(HResult.CLR_E_BIND_TYPE_NOT_FOUND), "A binding for the specified type name was not found.") },
                    { HResult.CLR_E_BIND_SYS_ASM_NI_MISSING, (nameof(HResult.CLR_E_BIND_SYS_ASM_NI_MISSING), "Could not use native image because Mscorlib.dll is missing a native image") },
                    { HResult.CLR_E_BIND_NI_SECURITY_FAILURE, (nameof(HResult.CLR_E_BIND_NI_SECURITY_FAILURE), "Native image was generated in a different trust level than present at runtime") },
                    { HResult.CLR_E_BIND_NI_DEP_IDENTITY_MISMATCH, (nameof(HResult.CLR_E_BIND_NI_DEP_IDENTITY_MISMATCH), "Native image identity mismatch with respect to its dependencies") },
                    { HResult.CLR_E_GC_OOM, (nameof(HResult.CLR_E_GC_OOM), "Failfast due to an OOM during a GC") },
                    { HResult.CLR_E_GC_BAD_AFFINITY_CONFIG, (nameof(HResult.CLR_E_GC_BAD_AFFINITY_CONFIG), "GCHeapAffinitizeMask or GCHeapAffinitizeRanges didn't specify any CPUs the current process is affinitized to.") },
                    { HResult.CLR_E_GC_BAD_AFFINITY_CONFIG_FORMAT, (nameof(HResult.CLR_E_GC_BAD_AFFINITY_CONFIG_FORMAT), "GCHeapAffinitizeRanges configuration string has invalid format.") },
                    { HResult.CLR_E_CROSSGEN_NO_IBC_DATA_FOUND, (nameof(HResult.CLR_E_CROSSGEN_NO_IBC_DATA_FOUND), "Cannot compile using the PartialNgen flag because no IBC data was found.") },
                    { HResult.COR_E_UNAUTHORIZEDACCESS, (nameof(HResult.COR_E_UNAUTHORIZEDACCESS), "Access is denied.") },
                    { HResult.COR_E_ARGUMENT, (nameof(HResult.COR_E_ARGUMENT), "An argument does not meet the contract of the method.") },
                    { HResult.COR_E_INVALIDCAST, (nameof(HResult.COR_E_INVALIDCAST), "Indicates a bad cast condition") },
                    { HResult.COR_E_OUTOFMEMORY, (nameof(HResult.COR_E_OUTOFMEMORY), "The EE thows this exception when no more memory is avaible to continue execution") },
                    { HResult.COR_E_NULLREFERENCE, (nameof(HResult.COR_E_NULLREFERENCE), "Dereferencing a null reference. In general class libraries should not throw this") },
                    { HResult.COR_E_ARITHMETIC, (nameof(HResult.COR_E_ARITHMETIC), "Overflow or underflow in mathematical operations.") },
                    { HResult.COR_E_PATHTOOLONG, (nameof(HResult.COR_E_PATHTOOLONG), "The specified path was too long.") },
                    { HResult.COR_E_FILENOTFOUND, (nameof(HResult.COR_E_FILENOTFOUND), "The system cannot find the file specified.") },
                    { HResult.COR_E_ENDOFSTREAM, (nameof(HResult.COR_E_ENDOFSTREAM), "Attempted to read past the end of the stream.") },
                    { HResult.COR_E_DIRECTORYNOTFOUND, (nameof(HResult.COR_E_DIRECTORYNOTFOUND), "The specified path couldn't be found.") },
                    { HResult.COR_E_STACKOVERFLOW, (nameof(HResult.COR_E_STACKOVERFLOW), "Is raised by the EE when the execution stack overflows as it is attempting to ex") },
                    { HResult.COR_E_AMBIGUOUSMATCH, (nameof(HResult.COR_E_AMBIGUOUSMATCH), "While late binding to a method via reflection, could not resolve between") },
                    { HResult.COR_E_TARGETPARAMCOUNT, (nameof(HResult.COR_E_TARGETPARAMCOUNT), "There was a mismatch between number of arguments provided and the number expected") },
                    { HResult.COR_E_DIVIDEBYZERO, (nameof(HResult.COR_E_DIVIDEBYZERO), "Attempted to divide a number by zero.") },
                    { HResult.COR_E_BADIMAGEFORMAT, (nameof(HResult.COR_E_BADIMAGEFORMAT), "The format of a DLL or executable being loaded is invalid.") },
                };
            }
        }
    }
}
